### ISSUE TITLE
[Bug]: Doesn't run on macos 10.14

### ISSUE THREAD

**Issue by FrostBird347** [DmitriySalnikov/godot_qoi#9] opened 2023-05-10 10:05 UTC
### Godot version

4.0.2

### godot_qoi version

2.0.3

### On which operating systems the error occurs

macOS

### Using which renderers the error occurs

GLES3

### Issue description

I had previously tried this extension on godot 3 without issue, however the latest version now fails to load on godot 4.0.2.

The console output is spammed with these error logs:
```
  Can't open dynamic library: /Users/[REMOVED]/Project/addons/godot_qoi/libs/macos/libgodot_qoi.macos.template_debug.universal.dylib, error: dlopen(/Users/[REMOVED]/Project/addons/godot_qoi/libs/macos/libgodot_qoi.macos.template_debug.universal.dylib, 2): no suitable image found.  Did find:
  	/Users/[REMOVED]/Project/addons/godot_qoi/libs/macos/libgodot_qoi.macos.template_debug.universal.dylib: cannot load 'libgodot_qoi.macos.template_debug.universal.dylib' (load command 0x80000034 is unknown)
  	/Users/[REMOVED]/Project/addons/godot_qoi/libs/macos/libgodot_qoi.macos.template_debug.universal.dylib: cannot load 'libgodot_qoi.macos.template_debug.universal.dylib' (load command 0x80000034 is unknown).
  core/extension/gdextension.cpp:400 - GDExtension dynamic library not found: /Users/[REMOVED]/Project/addons/godot_qoi/libs/macos/libgodot_qoi.macos.template_debug.universal.dylib
  Failed loading resource: res://addons/godot_qoi/qoi.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

### Steps to reproduce

1. Install the plugin on godot 4, on macos 10.14
2. Observe load error window popup and the errors listed above in the output log ![error](https://github.com/DmitriySalnikov/godot_qoi/assets/39435218/8b6597c5-1fae-47d1-9648-5a44bc4ef9d1)
3. Restart godot
4. Observe the load error window popup and same errors in the output log

### Minimal reproduction project

"N/A"

**Comment by DmitriySalnikov** [comment] 2023-05-11 04:52
I can only check in macOS 12.6.5, the newer one is not supported, and I don't want to install another version, because macOS on my virtual machine runs in 1 FPS...

Most likely the problem is that your macOS is much older than the version in which the library is being built (12.6.5).
Or maybe you have a 32bit version of macOS (dylib contains assemblies for x86_64 and arm64)? I do not know what bitness was in macOS 10.14.

PR is welcome.

**Comment by FrostBird347** [comment] 2023-05-11 09:20
macOS 10.14 is 64bit, with support for 32bit.

I know that you can tell the compiler to build for older macOS versions through the environment variable (`export MACOSX_DEPLOYMENT_TARGET=10.14`) and that gcc will prioritise the command line argument (`--mmacosx-version-min=10.14`) over the environment variable.

Unfortunately setting the environment variable before compiling via github actions hasn't had any effect (both outputted files have the same contents) and I haven't yet found a way to add that command line argument to the compiler.

**Comment by DmitriySalnikov** [comment] 2023-05-11 09:50
there was a separate option for this: https://github.com/godotengine/godot-cpp/blob/9d1c396c54fc3bdfcc7da4f3abcb52b14f6cce8f/tools/macos.py#LL7C10-L7C10

can you check this build? https://github.com/DmitriySalnikov/godot_qoi/actions/runs/4946400586

**Comment by FrostBird347** [comment] 2023-05-11 10:21
I can confirm that it runs and is able to import qoi files without any errors

**Comment by DmitriySalnikov** [comment] 2023-05-11 10:47
Everything seems to be working on my VM, too. I hope that with this on ARM devices everything will also work.
So I merge this change into the master branch and close this issue.

**Closed as completed by DmitriySalnikov** 2023-05-11 10:47 UTC
Labels: bug

**Comment by DmitriySalnikov** [comment] 2023-05-11 11:09
I also submitted an update to [AssetLib](https://godotengine.org/asset-library/asset/edit/7896). Thanks!
